pipeline {
    agent any
    triggers {
        upstream(upstreamProjects: "petition-stats-refresh-reports",
                 threshold: hudson.model.Result.SUCCESS)
    }
    options {
        lock resource: "Docs"
    }
    environment {
        REPO = 'petition-stats-www'
    }
    stages {
        stage('Git Clone') {
            steps {
                sh """rm -fr ${REPO}
                      git clone --depth 1 https://github.com/Logiqx/${REPO}.git"""
            }
        }
        stage('Git Diff') {
            steps {
                sh """cd ${REPO}
                      cp -frp /home/jovyan/work/petition-stats/docs/open docs/
                      cp -frp /home/jovyan/work/petition-stats/docs/closed docs/
                      git diff --stat"""
            }
        }
        stage('Git Commit') {
            steps {
                sh """cd ${REPO}
                      git add docs/open docs/closed
                      git diff-index --quiet HEAD || git commit -m \"Refresh \$(date --rfc-2822)\""""
            }
        }
        stage('Git Push') {
            steps {
                sh """cd ${REPO}
                      git push"""
            }
        }
    }
    post {
        always {
            deleteDir()
        }
        failure {
            emailext(
                to: "${EMAIL_RECIPIENTS}",
                subject: "Failed Build: ${currentBuild.fullDisplayName}.",
                body: """<p>FAILURE: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'</p>
                         <p>See attachment for console output or visit this
                            <a href=\"${env.BUILD_URL}\">link</a>.</p>""",
                attachLog: true
            )
        }
    }
}
